/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export type TokenMetadataRequest = Array<bigint>;
export type Map_ = Array<[string, Value]>;
export type TokenMetadataResponse = Array<TokenMetadataItem>;
export type BalanceOfResponse = Array<bigint>;
export type BalanceOfRequest = Array<Account>;
export type OwnerOfRequest = Array<bigint>;
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export type CollectionMetadataResponse = Array<[string, Value]>;
export type Metadata = Array<[string, Value]>;
export interface TransferArg {
    to: Account;
    token_id: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
}
export type TransferResult = {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferError;
};
export type SupportedStandardsResponse = Array<{
    url: string;
    name: string;
}>;
export type OwnerOfResponse = Array<Account | null>;
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Map_;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
};
export type TokenMetadataItem = Metadata | null;
export type TransferError = {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "NonExistingTokenId";
    NonExistingTokenId: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "InvalidRecipient";
    InvalidRecipient: null;
} | {
    __kind__: "GenericBatchError";
    GenericBatchError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
};
export interface GERAMInterface {
    get_icrc85_stats(): Promise<{
        activeActions: bigint;
        nextCycleActionId?: bigint;
        lastActionReported?: bigint;
    }>;
    icrc7_atomic_batch_transfers(): Promise<boolean | null>;
    icrc7_balance_of(args: BalanceOfRequest): Promise<BalanceOfResponse>;
    icrc7_collection_metadata(): Promise<CollectionMetadataResponse>;
    icrc7_default_take_value(): Promise<bigint | null>;
    icrc7_description(): Promise<string | null>;
    icrc7_logo(): Promise<string | null>;
    icrc7_max_memo_size(): Promise<bigint | null>;
    icrc7_max_query_batch_size(): Promise<bigint | null>;
    icrc7_max_take_value(): Promise<bigint | null>;
    icrc7_max_update_batch_size(): Promise<bigint | null>;
    icrc7_name(): Promise<string>;
    icrc7_owner_of(args: OwnerOfRequest): Promise<OwnerOfResponse>;
    icrc7_permitted_drift(): Promise<bigint | null>;
    icrc7_supply_cap(): Promise<bigint | null>;
    icrc7_supported_standards(): Promise<SupportedStandardsResponse>;
    icrc7_symbol(): Promise<string>;
    icrc7_token_metadata(args: TokenMetadataRequest): Promise<TokenMetadataResponse>;
    icrc7_tokens(prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_tokens_of(account: Account, prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_total_supply(): Promise<bigint>;
    icrc7_transfer(args: Array<TransferArg>): Promise<Array<TransferResult | null>>;
    icrc7_tx_window(): Promise<bigint | null>;
}
export interface backendInterface extends GERAMInterface {
}
import type { Account as _Account, BalanceOfRequest as _BalanceOfRequest, CollectionMetadataResponse as _CollectionMetadataResponse, Map as _Map, Metadata as _Metadata, OwnerOfResponse as _OwnerOfResponse, TokenMetadataItem as _TokenMetadataItem, TokenMetadataResponse as _TokenMetadataResponse, TransferArg as _TransferArg, TransferError as _TransferError, TransferResult as _TransferResult, Value as _Value } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async get_icrc85_stats(): Promise<{
        activeActions: bigint;
        nextCycleActionId?: bigint;
        lastActionReported?: bigint;
    }> {
        const result = await this.actor.get_icrc85_stats();
        return from_candid_record_n1(result);
    }
    async icrc7_atomic_batch_transfers(): Promise<boolean | null> {
        const result = await this.actor.icrc7_atomic_batch_transfers();
        return from_candid_opt_n3(result);
    }
    async icrc7_balance_of(arg0: BalanceOfRequest): Promise<BalanceOfResponse> {
        const result = await this.actor.icrc7_balance_of(to_candid_BalanceOfRequest_n4(arg0));
        return result;
    }
    async icrc7_collection_metadata(): Promise<CollectionMetadataResponse> {
        const result = await this.actor.icrc7_collection_metadata();
        return from_candid_CollectionMetadataResponse_n8(result);
    }
    async icrc7_default_take_value(): Promise<bigint | null> {
        const result = await this.actor.icrc7_default_take_value();
        return from_candid_opt_n2(result);
    }
    async icrc7_description(): Promise<string | null> {
        const result = await this.actor.icrc7_description();
        return from_candid_opt_n15(result);
    }
    async icrc7_logo(): Promise<string | null> {
        const result = await this.actor.icrc7_logo();
        return from_candid_opt_n15(result);
    }
    async icrc7_max_memo_size(): Promise<bigint | null> {
        const result = await this.actor.icrc7_max_memo_size();
        return from_candid_opt_n2(result);
    }
    async icrc7_max_query_batch_size(): Promise<bigint | null> {
        const result = await this.actor.icrc7_max_query_batch_size();
        return from_candid_opt_n2(result);
    }
    async icrc7_max_take_value(): Promise<bigint | null> {
        const result = await this.actor.icrc7_max_take_value();
        return from_candid_opt_n2(result);
    }
    async icrc7_max_update_batch_size(): Promise<bigint | null> {
        const result = await this.actor.icrc7_max_update_batch_size();
        return from_candid_opt_n2(result);
    }
    async icrc7_name(): Promise<string> {
        const result = await this.actor.icrc7_name();
        return result;
    }
    async icrc7_owner_of(arg0: OwnerOfRequest): Promise<OwnerOfResponse> {
        const result = await this.actor.icrc7_owner_of(arg0);
        return from_candid_OwnerOfResponse_n16(result);
    }
    async icrc7_permitted_drift(): Promise<bigint | null> {
        const result = await this.actor.icrc7_permitted_drift();
        return from_candid_opt_n2(result);
    }
    async icrc7_supply_cap(): Promise<bigint | null> {
        const result = await this.actor.icrc7_supply_cap();
        return from_candid_opt_n2(result);
    }
    async icrc7_supported_standards(): Promise<SupportedStandardsResponse> {
        const result = await this.actor.icrc7_supported_standards();
        return result;
    }
    async icrc7_symbol(): Promise<string> {
        const result = await this.actor.icrc7_symbol();
        return result;
    }
    async icrc7_token_metadata(arg0: TokenMetadataRequest): Promise<TokenMetadataResponse> {
        const result = await this.actor.icrc7_token_metadata(arg0);
        return from_candid_TokenMetadataResponse_n22(result);
    }
    async icrc7_tokens(arg0: bigint | null, arg1: bigint | null): Promise<Array<bigint>> {
        const result = await this.actor.icrc7_tokens(to_candid_opt_n27(arg0), to_candid_opt_n27(arg1));
        return result;
    }
    async icrc7_tokens_of(arg0: Account, arg1: bigint | null, arg2: bigint | null): Promise<Array<bigint>> {
        const result = await this.actor.icrc7_tokens_of(to_candid_Account_n6(arg0), to_candid_opt_n27(arg1), to_candid_opt_n27(arg2));
        return result;
    }
    async icrc7_total_supply(): Promise<bigint> {
        const result = await this.actor.icrc7_total_supply();
        return result;
    }
    async icrc7_transfer(arg0: Array<TransferArg>): Promise<Array<TransferResult | null>> {
        const result = await this.actor.icrc7_transfer(to_candid_vec_n28(arg0));
        return from_candid_vec_n31(result);
    }
    async icrc7_tx_window(): Promise<bigint | null> {
        const result = await this.actor.icrc7_tx_window();
        return from_candid_opt_n2(result);
    }
}
function from_candid_Account_n19(value: _Account): Account {
    return from_candid_record_n20(value);
}
function from_candid_CollectionMetadataResponse_n8(value: _CollectionMetadataResponse): CollectionMetadataResponse {
    return from_candid_vec_n9(value);
}
function from_candid_Map_n13(value: _Map): Map_ {
    return from_candid_vec_n9(value);
}
function from_candid_Metadata_n26(value: _Metadata): Metadata {
    return from_candid_vec_n9(value);
}
function from_candid_OwnerOfResponse_n16(value: _OwnerOfResponse): OwnerOfResponse {
    return from_candid_vec_n17(value);
}
function from_candid_TokenMetadataItem_n24(value: _TokenMetadataItem): TokenMetadataItem {
    return from_candid_opt_n25(value);
}
function from_candid_TokenMetadataResponse_n22(value: _TokenMetadataResponse): TokenMetadataResponse {
    return from_candid_vec_n23(value);
}
function from_candid_TransferError_n35(value: _TransferError): TransferError {
    return from_candid_variant_n36(value);
}
function from_candid_TransferResult_n33(value: _TransferResult): TransferResult {
    return from_candid_variant_n34(value);
}
function from_candid_Value_n11(value: _Value): Value {
    return from_candid_variant_n12(value);
}
function from_candid_opt_n15(value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n19(value[0]);
}
function from_candid_opt_n2(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(value: [] | [_Metadata]): Metadata | null {
    return value.length === 0 ? null : from_candid_Metadata_n26(value[0]);
}
function from_candid_opt_n3(value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(value: [] | [_TransferResult]): TransferResult | null {
    return value.length === 0 ? null : from_candid_TransferResult_n33(value[0]);
}
function from_candid_record_n1(value: {
    activeActions: bigint;
    nextCycleActionId: [] | [bigint];
    lastActionReported: [] | [bigint];
}): {
    activeActions: bigint;
    nextCycleActionId?: bigint;
    lastActionReported?: bigint;
} {
    return {
        activeActions: value.activeActions,
        nextCycleActionId: record_opt_to_undefined(from_candid_opt_n2(value.nextCycleActionId)),
        lastActionReported: record_opt_to_undefined(from_candid_opt_n2(value.lastActionReported))
    };
}
function from_candid_record_n20(value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n21(value.subaccount))
    };
}
function from_candid_tuple_n10(value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n11(value[1])
    ];
}
function from_candid_variant_n12(value: {
    Int: bigint;
} | {
    Map: _Map;
} | {
    Nat: bigint;
} | {
    Blob: Uint8Array;
} | {
    Text: string;
} | {
    Array: Array<_Value>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Map_;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<Value>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_Map_n13(value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n14(value.Array)
    } : value;
}
function from_candid_variant_n34(value: {
    Ok: bigint;
} | {
    Err: _TransferError;
}): {
    __kind__: "Ok";
    Ok: bigint;
} | {
    __kind__: "Err";
    Err: TransferError;
} {
    return "Ok" in value ? {
        __kind__: "Ok",
        Ok: value.Ok
    } : "Err" in value ? {
        __kind__: "Err",
        Err: from_candid_TransferError_n35(value.Err)
    } : value;
}
function from_candid_variant_n36(value: {
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    NonExistingTokenId: null;
} | {
    Unauthorized: null;
} | {
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    InvalidRecipient: null;
} | {
    GenericBatchError: {
        message: string;
        error_code: bigint;
    };
} | {
    TooOld: null;
}): {
    __kind__: "GenericError";
    GenericError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "Duplicate";
    Duplicate: {
        duplicate_of: bigint;
    };
} | {
    __kind__: "NonExistingTokenId";
    NonExistingTokenId: null;
} | {
    __kind__: "Unauthorized";
    Unauthorized: null;
} | {
    __kind__: "CreatedInFuture";
    CreatedInFuture: {
        ledger_time: bigint;
    };
} | {
    __kind__: "InvalidRecipient";
    InvalidRecipient: null;
} | {
    __kind__: "GenericBatchError";
    GenericBatchError: {
        message: string;
        error_code: bigint;
    };
} | {
    __kind__: "TooOld";
    TooOld: null;
} {
    return "GenericError" in value ? {
        __kind__: "GenericError",
        GenericError: value.GenericError
    } : "Duplicate" in value ? {
        __kind__: "Duplicate",
        Duplicate: value.Duplicate
    } : "NonExistingTokenId" in value ? {
        __kind__: "NonExistingTokenId",
        NonExistingTokenId: value.NonExistingTokenId
    } : "Unauthorized" in value ? {
        __kind__: "Unauthorized",
        Unauthorized: value.Unauthorized
    } : "CreatedInFuture" in value ? {
        __kind__: "CreatedInFuture",
        CreatedInFuture: value.CreatedInFuture
    } : "InvalidRecipient" in value ? {
        __kind__: "InvalidRecipient",
        InvalidRecipient: value.InvalidRecipient
    } : "GenericBatchError" in value ? {
        __kind__: "GenericBatchError",
        GenericBatchError: value.GenericBatchError
    } : "TooOld" in value ? {
        __kind__: "TooOld",
        TooOld: value.TooOld
    } : value;
}
function from_candid_vec_n14(value: Array<_Value>): Array<Value> {
    return value.map((x)=>from_candid_Value_n11(x));
}
function from_candid_vec_n17(value: Array<[] | [_Account]>): Array<Account | null> {
    return value.map((x)=>from_candid_opt_n18(x));
}
function from_candid_vec_n23(value: Array<_TokenMetadataItem>): Array<TokenMetadataItem> {
    return value.map((x)=>from_candid_TokenMetadataItem_n24(x));
}
function from_candid_vec_n31(value: Array<[] | [_TransferResult]>): Array<TransferResult | null> {
    return value.map((x)=>from_candid_opt_n32(x));
}
function from_candid_vec_n9(value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n10(x));
}
function to_candid_Account_n6(value: Account): _Account {
    return to_candid_record_n7(value);
}
function to_candid_BalanceOfRequest_n4(value: BalanceOfRequest): _BalanceOfRequest {
    return to_candid_vec_n5(value);
}
function to_candid_TransferArg_n29(value: TransferArg): _TransferArg {
    return to_candid_record_n30(value);
}
function to_candid_opt_n27(value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n30(value: {
    to: Account;
    token_id: bigint;
    memo?: Uint8Array;
    from_subaccount?: Uint8Array;
    created_at_time?: bigint;
}): {
    to: _Account;
    token_id: bigint;
    memo: [] | [Uint8Array];
    from_subaccount: [] | [Uint8Array];
    created_at_time: [] | [bigint];
} {
    return {
        to: to_candid_Account_n6(value.to),
        token_id: value.token_id,
        memo: value.memo ? candid_some(value.memo) : candid_none(),
        from_subaccount: value.from_subaccount ? candid_some(value.from_subaccount) : candid_none(),
        created_at_time: value.created_at_time ? candid_some(value.created_at_time) : candid_none()
    };
}
function to_candid_record_n7(value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
function to_candid_vec_n28(value: Array<TransferArg>): Array<_TransferArg> {
    return value.map((x)=>to_candid_TransferArg_n29(x));
}
function to_candid_vec_n5(value: Array<Account>): Array<_Account> {
    return value.map((x)=>to_candid_Account_n6(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
