/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Certificate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'value' : IDL.Nat,
    'owner' : IDL.Principal,
    'metadata' : IDL.Text,
    'issuer' : IDL.Principal,
    'image' : IDL.Text,
    'issuedAt' : IDL.Int,
    'externalUrl' : IDL.Text,
    'certificateType' : IDL.Text,
  });
  
  return IDL.Service({
    'getCertificate' : IDL.Func([IDL.Text], [IDL.Opt(Certificate)], ['query']),
    'getOwner' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Principal)], ['query']),
    'issueCertificate' : IDL.Func(
        [
          IDL.Text,
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'transferCertificate' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Bool], []),
    'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };