/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Certificate {
  'id' : string,
  'title' : string,
  'active' : boolean,
  'value' : bigint,
  'owner' : Principal,
  'metadata' : string,
  'issuer' : Principal,
  'image' : string,
  'issuedAt' : bigint,
  'externalUrl' : string,
  'certificateType' : string,
}
export interface _SERVICE {
  'getCertificate' : ActorMethod<[string], [] | [Certificate]>,
  'getOwner' : ActorMethod<[string], [] | [Principal]>,
  'issueCertificate' : ActorMethod<
    [string, Principal, string, string, bigint, string, string, string],
    boolean
  >,
  'transferCertificate' : ActorMethod<[string, Principal], boolean>,
  'verifyCertificate' : ActorMethod<[string], boolean>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];