/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.4.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface Certificate {
    id: string;
    title: string;
    active: boolean;
    value: bigint;
    owner: Principal;
    metadata: string;
    issuer: Principal;
    image: string;
    issuedAt: bigint;
    externalUrl: string;
    certificateType: string;
}
export interface backendInterface {
    getCertificate(arg0: string): Promise<Certificate | null>;
    getOwner(arg0: string): Promise<Principal | null>;
    issueCertificate(arg0: string, arg1: Principal, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<boolean>;
    transferCertificate(arg0: string, arg1: Principal): Promise<boolean>;
    verifyCertificate(arg0: string): Promise<boolean>;
}
import type { Certificate as _Certificate } from "./declarations/backend.did";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async getCertificate(arg0: string): Promise<Certificate | null> {
        const result = await this.actor.getCertificate(arg0);
        return from_candid_opt_n1(result);
    }
    async getOwner(arg0: string): Promise<Principal | null> {
        const result = await this.actor.getOwner(arg0);
        return from_candid_opt_n2(result);
    }
    async issueCertificate(arg0: string, arg1: Principal, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<boolean> {
        const result = await this.actor.issueCertificate(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
        return result;
    }
    async transferCertificate(arg0: string, arg1: Principal): Promise<boolean> {
        const result = await this.actor.transferCertificate(arg0, arg1);
        return result;
    }
    async verifyCertificate(arg0: string): Promise<boolean> {
        const result = await this.actor.verifyCertificate(arg0);
        return result;
    }
}
function from_candid_opt_n1(value: [] | [_Certificate]): Certificate | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
